(function () {
  const root = window.NusukAutofill = window.NusukAutofill || {};

  const NEXT_BUTTON_CANDIDATE_SELECTORS = [
    ".d-flex.justify-content-end.align-items-center.gap-3 > button.btn.btn-primary:has-text('Next')",
    "action-btns.custom-action-buttons .d-flex.justify-content-end.align-items-center.gap-3 > button.btn.btn-primary:has-text('Next')",
    "action-btns.custom-action-buttons button.btn.btn-primary:has-text('Next')",
    "action-btns button.btn.btn-primary:has-text('Next')",
    ".action-buttons .navigation-buttons button:has-text('Next')",
  ];

  root.constants = Object.freeze({
    STORAGE_KEY: "nusukAutofillState",
    PANEL_FRAME_ID: "nusuk-autofill-panel-frame",
    PANEL_HOST_ID: "nusuk-autofill-panel-host",
    PANEL_TOGGLE_ID: "nusuk-autofill-panel-toggle",
    PANEL_RESIZE_HANDLE_ID: "nusuk-autofill-panel-resize",
    HIGHLIGHT_STYLE_ID: "nusuk-autofill-highlight-style",
    ACTIVE_HIGHLIGHT_CLASS: "nusuk-autofill-active-field",
    PANEL_ORIGIN: chrome.runtime.getURL("").replace(/\/$/, ""),
    PANEL_WIDTH_MIN: 300,
    PANEL_WIDTH_MAX: 600,
    PANEL_WIDTH_DEFAULT: 420,
    DEFAULT_REPO_ROOT: "C:\\visa-entry-bot",
    WINDOWS_ABSOLUTE_PATH_RE: /^[a-zA-Z]:[\\/]/,
    FILE_URI_RE: /^file:\/\//i,
    AUTOFILL_MODE_LABEL: "cepat natural",
    SLOW_MODE_ENABLED: true,
    STEP_BEFORE_DELAY_MS: 260,
    STEP_AFTER_DELAY_MS: 380,
    CLICK_SETTLE_DELAY_MS: 560,
    FILL_SETTLE_DELAY_MS: 280,
    DROPDOWN_SETTLE_DELAY_MS: 620,
    UPLOAD_SETTLE_DELAY_MS: 850,
    UPLOAD_AFTER_DELAY_MS: 300,
    WAIT_SETTLE_DELAY_MS: 220,
    WAIT_POLL_INTERVAL_MS: 80,
    PAGE_READY_POLL_INTERVAL_MS: 80,
    PAGE_READY_STABLE_MS: 500,
    HUMAN_DEFAULT_DELAY_MS: 160,
    HUMAN_DEFAULT_JITTER_MS: 160,
    HUMAN_CLICK_DELAY_MS: 240,
    HUMAN_CLICK_JITTER_MS: 180,
    HUMAN_UPLOAD_DELAY_MS: 360,
    HUMAN_UPLOAD_JITTER_MS: 220,
    AUTOFILL_MAX_RETRIES_PER_MEMBER: 3,
    AUTOFILL_RETRY_BASE_DELAY_MS: 2000,
    AUTOFILL_RETRY_MAX_DELAY_MS: 15000,
    AUTOFILL_MEMBER_WATCHDOG_MS: 180000,
    AUTOFILL_SESSION_RECOVERY_WAIT_MS: 180000,
    UPLOAD_MIN_TARGET_BYTES: 0,
    UPLOAD_MAX_BYTES: 1024 * 1024,
    PASSPORT_UPLOAD_SELECTOR: [
      ".passport-upload-section input[type='file']",
      ".passport-upload-section .upload-container input[type='file']",
      ".passport-upload-section button:has-text('Choose File')",
      ".upload-container input[type='file']",
      ".upload-container button:has-text('Choose File')",
      ".container__notes__upload__button input[type='file']",
      ".container__notes__upload input[type='file']",
      ".upload-button input[type='file']",
      "div[class*='upload' i] input[type='file']",
      "input[type='file'][formcontrolname*='passport' i]",
      "input[type='file'][name*='passport' i]",
      "input[type='file'][id*='passport' i]",
      "input[type='file'][accept*='image' i]",
      "input[type='file'][accept*='.png' i]",
      "input[type='file'][accept*='.jpg' i]",
      "input[type='file'][accept*='.jpeg' i]",
      "input[type='file'][accept*='.pdf' i]",
      "input[type='file']",
    ].join(", "),
    NEXT_BUTTON_CANDIDATE_SELECTORS,
    NEXT_BUTTON_SELECTOR: NEXT_BUTTON_CANDIDATE_SELECTORS.join(", "),
    VACCINATION_UPLOAD_SELECTOR: [
      "input[type='file'][formcontrolname='vaccinationPicture']",
      "input[type='file'][name='vaccinationPicture']",
      "input[type='file'][formcontrolname*='vaccin' i]",
      "input[type='file'][name*='vaccin' i]",
      "input[type='file'][id*='vaccin' i]",
      "input[type='file'][formcontrolname*='vaccine' i]",
      "input[type='file'][name*='vaccine' i]",
      "input[type='file'][id*='vaccine' i]",
      "input[type='file'][formcontrolname*='immun' i]",
      "input[type='file'][name*='immun' i]",
      "input[type='file'][id*='immun' i]",
    ].join(", "),
    MOBILE_NUMBER_SELECTOR: [
      "input[formcontrolname='phone']",
      "input[name='phone']",
      "input[formcontrolname='mobileNumber']",
      "input[name='mobileNumber']",
      "input[formcontrolname='mobileNo']",
      "input[name='mobileNo']",
      "input[formcontrolname='phoneNumber']",
      "input[name='phoneNumber']",
      "input[formcontrolname*='mobile' i]",
      "input[name*='mobile' i]",
      "input[id*='mobile' i]",
      "input[formcontrolname*='phone' i]",
      "input[name*='phone' i]",
      "input[id*='phone' i]",
      "input[placeholder='Mobile Number']",
      "input[placeholder='Phone Number']",
      "input[placeholder*='Phone' i]",
      "input[placeholder*='Mobile' i]",
      "input[aria-label*='Phone' i]",
      "input[aria-label*='Mobile' i]",
      ".phone-field .phone-input",
      "input.phone-input",
      "input[type='tel']",
      "input[inputmode='tel']",
      "ngx-intl-tel-input input",
    ].join(", "),
    IQAMA_FIELD_SELECTOR: [
      "input[formcontrolname*='iqama' i]",
      "input[formcontrolname*='residency' i]",
      "input[formcontrolname*='residence' i]",
      "input[formcontrolname*='resident' i]",
      "input[name*='iqama' i]",
      "input[name*='residency' i]",
      "input[name*='residence' i]",
      "input[name*='resident' i]",
      "input[id*='iqama' i]",
      "input[id*='residency' i]",
      "input[id*='residence' i]",
      "input[id*='resident' i]",
      "input[placeholder*='Iqama' i]",
      "input[placeholder*='Residency' i]",
      "input[placeholder*='Residence' i]",
      "input[placeholder*='Resident' i]",
      "input[aria-label*='Iqama' i]",
      "input[aria-label*='Residency' i]",
      "input[aria-label*='Residence' i]",
      "input[aria-label*='Resident' i]",
      "p-calendar[formcontrolname*='iqama' i] input",
      "p-calendar[formcontrolname*='residency' i] input",
      "p-calendar[formcontrolname*='residence' i] input",
      "p-calendar[formcontrolname*='resident' i] input",
    ].join(", "),
  });
})();
