import type { LucideIcon } from 'lucide-react';
import {
  AlertTriangle,
  AppWindow,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  Crop,
  Download,
  ExternalLink,
  FileOutput,
  FileText,
  Folder,
  FolderOpen,
  Gauge,
  Hourglass,
  Images,
  Info,
  ListChecks,
  Mail,
  Maximize2,
  Minimize2,
  Minus,
  PanelLeftClose,
  PanelLeftOpen,
  Phone,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  RotateCw,
  ScanLine,
  Search,
  Square,
  StopCircle,
  Terminal,
  Trash2,
  Upload,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  alert: AlertTriangle,
  error: AlertTriangle,
  warning: AlertTriangle,
  app: AppWindow,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  book: BookOpen,
  menu_book: BookOpen,
  briefcase: BriefcaseBusiness,
  work: BriefcaseBusiness,
  blinds: AppWindow,
  calendar: CalendarDays,
  check: Check,
  check_all: CheckCheck,
  done_all: CheckCheck,
  check_circle: CheckCircle2,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  review: ClipboardCheck,
  crop: Crop,
  download: Download,
  system_update: Download,
  external_link: ExternalLink,
  export: FileOutput,
  file: FileText,
  description: FileText,
  folder: Folder,
  folder_open: FolderOpen,
  folder_special: FolderOpen,
  gauge: Gauge,
  hourglass: Hourglass,
  schedule: Hourglass,
  images: Images,
  photo_library: Images,
  info: Info,
  checklist: ListChecks,
  select_all: ListChecks,
  deselect: Square,
  mail: Mail,
  contact_mail: Mail,
  maximize: Maximize2,
  minimize: Minimize2,
  compress: Minimize2,
  minus: Minus,
  panel_close: PanelLeftClose,
  panel_open: PanelLeftOpen,
  phone: Phone,
  call: Phone,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  rocket: Rocket,
  rocket_launch: Rocket,
  rotate_left: RotateCcw,
  rotate_right: RotateCw,
  scan: ScanLine,
  search: Search,
  square: Square,
  stop: StopCircle,
  stop_circle: StopCircle,
  terminal: Terminal,
  trash: Trash2,
  delete: Trash2,
  upload: Upload,
  user: User,
  person: User,
  users: Users,
  group: Users,
  public: Gauge,
  translate: BookOpen,
  navigate_next: ChevronRight,
  close: X,
  zap: Zap,
};

interface AppIconProps {
  name: keyof typeof icons | string;
  size?: number;
  strokeWidth?: number;
  className?: string;
  'aria-hidden'?: boolean;
}

export default function AppIcon({
  name,
  size = 18,
  strokeWidth = 1.8,
  className,
  'aria-hidden': ariaHidden = true,
}: AppIconProps) {
  const Icon = icons[name] || Info;
  return (
    <Icon
      aria-hidden={ariaHidden}
      className={className}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}
