/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-bright": "#f7f9fb",
              "primary": "#004ac6",
              "on-tertiary-container": "#e4f2ff",
              "on-secondary-fixed-variant": "#38485d",
              "tertiary": "#005a82",
              "primary-container": "#2563eb",
              "on-secondary-fixed": "#0b1c30",
              "on-primary-fixed": "#00174b",
              "secondary-container": "#d0e1fb",
              "inverse-surface": "#2d3133",
              "inverse-primary": "#b4c5ff",
              "surface-tint": "#0053db",
              "on-primary-container": "#eeefff",
              "tertiary-fixed": "#c9e6ff",
              "surface-container-highest": "#e0e3e5",
              "on-surface-variant": "#434655",
              "background": "#f7f9fb",
              "surface-container-low": "#f2f4f6",
              "on-error": "#ffffff",
              "on-tertiary-fixed": "#001e2f",
              "surface": "#f7f9fb",
              "secondary": "#505f76",
              "tertiary-fixed-dim": "#89ceff",
              "secondary-fixed-dim": "#b7c8e1",
              "error": "#ba1a1a",
              "outline-variant": "#c3c6d7",
              "on-tertiary-fixed-variant": "#004c6e",
              "surface-container": "#eceef0",
              "on-secondary": "#ffffff",
              "secondary-fixed": "#d3e4fe",
              "on-surface": "#191c1e",
              "error-container": "#ffdad6",
              "surface-variant": "#e0e3e5",
              "primary-fixed": "#dbe1ff",
              "primary-fixed-dim": "#b4c5ff",
              "on-primary-fixed-variant": "#003ea8",
              "on-secondary-container": "#54647a",
              "on-primary": "#ffffff",
              "tertiary-container": "#0074a6",
              "surface-container-high": "#e6e8ea",
              "inverse-on-surface": "#eff1f3",
              "on-background": "#191c1e",
              "outline": "#737686",
              "on-tertiary": "#ffffff",
              "surface-dim": "#d8dadc",
              "surface-container-lowest": "#ffffff",
              "on-error-container": "#93000a"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-x": "32px",
              "card-padding": "24px",
              "gutter": "24px",
              "container-max": "1440px",
              "stack-sm": "8px",
              "stack-md": "16px",
              "stack-lg": "24px"
      },
      "fontFamily": {
              "body-lg": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "body-sm": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "headline-lg": ["Hanken Grotesk", "sans-serif"],
              "label-sm": ["Inter", "sans-serif"],
              "headline-xl": ["Hanken Grotesk", "sans-serif"],
              "headline-md": ["Hanken Grotesk", "sans-serif"],
              "code": ["Inter", "monospace"]
      },
      "fontSize": {
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
              "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "headline-md": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
              "code": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
